### ISSUE TITLE
Facebook page not showing in Firefox

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/facebook_page#1]
My facebook page is being successfully embedded as a block and is visible in Chrome and Edge, but Firefox is not displaying it. Do you know of any way to prevent Firefox from supressing it?

**Comment by ghost** [comment]
Firefox may be blocking the JS necessary to display it. Try turning off their Enhanced Tracking Protection: https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop#w_what-to-do-if-a-site-seems-broken

**Comment by Graham-72** [comment]
Thanks. Firefox was telling me that Enhanced Tracking Protection was off
for the site. But now that I have cleared that setting and reset it, the JS
is working, as also is FB's iframe embedding code. But of course I cannot
expect other site visitors to know to do this. Setting ETP on by default is
a black mark for Firefox in my opinion.

Thanks for your help.
